export const INTERESTED_AREAS = [
    "Agriculture, Food & Natural Resources",
    "Architecture & Construction",
    "Arts, Audio/Video Technology & Communications",
    "Business Management & Administration",
    "Education & Training",
    "Finance",
    "Government & Public Administration",
    "Health Science",
    "Hospitality & Tourism",
    "Human Services",
    "Information Technology",
    "Law, Public Safety, Corrections & Security",
    "Manufacturing",
    "Marketing",
    "Science, Technology, Engineering & Mathematics (STEM)",
    "Transportation, Distribution & Logistics",
    "Medicine",
    "Dentistry",
    "Pharmacy",
    "Nursing",
    "Social Work",
    "Psychology",
    "Sociology",
    "Economics",
    "Political Science",
    "History",
    "Philosophy",
    "Religious Studies",
    "Modern Languages",
    "Classics",
    "Archaeology",
    "Anthropology",
    "Geography",
    "Environmental Science",
    "Biology",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Statistics",
    "Computer Science",
    "Software Engineering",
    "Cybersecurity",
    "Data Science",
    "Artificial Intelligence",
    "Robotics",
    "Aerospace Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Industrial Engineering",
    "Biomedical Engineering",
    "Accounting",
    "Actuarial Science",
    "Banking and Finance",
    "Real Estate",
    "Entrepreneurship",
    "Human Resource Management",
    "International Business",
    "Supply Chain Management",
    "Journalism",
    "Public Relations",
    "Graphic Design",
    "Interior Design",
    "Fashion Design",
    "Music",
    "Theater and Drama",
    "Film and Television",
    "Culinary Arts",
    "Sports Management"
].sort();

export const INTERESTED_COURSES = [
    "BSc Computer Science",
    "BEng Software Engineering",
    "BSc Information Technology",
    "BSc Data Science and Analytics",
    "BSc Cybersecurity",
    "BEng Electrical and Electronic Engineering",
    "BEng Mechanical Engineering",
    "BEng Civil Engineering",
    "BEng Chemical Engineering",
    "BEng Aerospace Engineering",
    "BEng Mechatronics and Robotics",
    "BEng Biomedical Engineering",
    "BSc Mathematics",
    "BSc Statistics",
    "BSc Physics",
    "BSc Chemistry",
    "BSc Biology",
    "BSc Biochemistry",
    "BSc Biotechnology",
    "BSc Environmental Science",
    "Bachelor of Medicine and Bachelor of Surgery (MBBS)",
    "Bachelor of Dental Surgery (BDS)",
    "Bachelor of Pharmacy (BPharm)",
    "BSc Nursing",
    "BSc Physiotherapy",
    "BSc Occupational Therapy",
    "BSc Radiography",
    "Bachelor of Architecture (BArch)",
    "BA Architecture",
    "BSc Economics",
    "BSc Accounting and Finance",
    "BSc Banking and International Finance",
    "Bachelor of Business Administration (BBA)",
    "BSc Business Management",
    "BSc Marketing",
    "BSc International Business",
    "BSc Supply Chain Management and Logistics",
    "Bachelor of Laws (LLB)",
    "BA Psychology",
    "BSc Psychology",
    "BA Sociology",
    "BA Political Science and International Relations",
    "BA History",
    "BA Philosophy",
    "BA English Literature",
    "BA Journalism and Mass Communication",
    "BA Graphic Design",
    "BA Fine Art",
    "BA Fashion Design",
    "BA Interior Design",
    "BA Music",
    "BA Drama and Performance",
    "BA Film and Television Production",
    "BEd Education (Primary)",
    "BEd Education (Secondary)",
    "BA Childhood Studies",
    "BSc Sports and Exercise Science",
    "BSc Sports Management",
    "BSc Hospitality and Tourism Management",
    "BSc Culinary Arts Management",
    "BSc Real Estate",
    "BSc Quantity Surveying",
    "BSc Construction Management",
    "BSc Agriculture",
    "BSc Food Science and Technology",
    "BSc Animal Science",
    "BSc Forestry",
    "BSc Marine Biology",
    "BSc Geology",
    "BSc Actuarial Science"
].sort();
